# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Zarifboyev"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Telegram"
name = "Welcome to WikiExplorer"
url = "https://t.me/WikiExplorer"

[social.params]
icon = "brand-telegram"

[[social]]
identifier = "Medium"
name = "Welcome to my Medium blog"
url = "http://zarifboyev.medium.com/"

[social.params]
icon = "brand-medium"

[[social]]
identifier = "Gmail"
name = "Feel free to contact me"
url = "https://mail.google.com/mail/?view=cm&fs=1&to=zarifboyev@duck.com"

[social.params]
icon = "brand-gmail"
